In [278]:
import numpy as np

In [279]:
matrix = np.array([[0,1,1,0],
                   [1,0,0,1],
                   [1,0,0,1],
                   [0,1,1,0]])

In [280]:
n = len(matrix[0])
final = matrix

In [281]:
for i in range(1,n-1):
    matrix = np.dot(matrix,matrix)
    order = i+1
    print(f"matrix of order: {order}")
    print(matrix)
    final+=matrix

matrix of order: 2
[[2 0 0 2]
 [0 2 2 0]
 [0 2 2 0]
 [2 0 0 2]]
matrix of order: 3
[[8 0 0 8]
 [0 8 8 0]
 [0 8 8 0]
 [8 0 0 8]]


In [282]:
print(final)

[[10  1  1 10]
 [ 1 10 10  1]
 [ 1 10 10  1]
 [10  1  1 10]]


In [283]:
print(np.any(final == 0))

False


In [284]:
import numpy as np

def check_connect(matrix):
    n = matrix.shape[0]
    final = matrix.copy()
    
    for i in range(1, n-1):
        matrix = np.dot(matrix, matrix)
        final += matrix

    return "Connected Graph" if (np.any(final == 0)) else "Disconnected Graph"

check_connect(matrix)


'Connected Graph'